runtime: nodejs20

instance_class: F1
service: client

automatic_scaling:
  max_instances: 3 

handlers:
  - url: /static
    static_dir: static
    secure: always

  - url: /(.*\.(json|ico|js|css|png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot))$
    static_files: \1
    upload: .*\.(json|ico|js|css|png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot)$
    secure: always

  - url: /.*
    static_files: index.html
    upload: index.html
    secure: always

env_variables:
  NODE_ENV: 'production'