runtime: nodejs20
instance_class: F1
service: server

env_variables:
  NODE_ENV: 'production'

handlers:
  - url: /.*
    script: auto
    secure: always

# Optional: Configure scaling settings as needed
automatic_scaling:
  min_instances: 0 
  max_instances: 1 
  target_cpu_utilization: 0.65