name: Build and Deploy to Google App Engine

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:    # Allows manual triggering

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Client build
      - name: Install client dependencies
        run: npm ci
        working-directory: ./client

      - name: Build client
        run: npm run build
        working-directory: ./client

      # Server build
      - name: Install server dependencies
        run: npm ci
        working-directory: ./server

      # Setup Google Cloud Auth
      - name: Auth with Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}

      # Deploy client to GAE
      - name: Deploy client to App Engine
        id: deploy-client
        uses: google-github-actions/deploy-appengine@v2
        with:
          working_directory: ./client
          deliverables: app.yaml
          project_id: ${{ secrets.GCP_PROJECT }}

      # Deploy server to GAE
      - name: Deploy server to App Engine
        id: deploy-server
        uses: google-github-actions/deploy-appengine@v2
        with:
          working_directory: ./server
          deliverables: app.yaml
          project_id: ${{ secrets.GCP_PROJECT }}

      # Output URLs
      - name: Show deployment URLs
        run: |
          echo "Client deployed to: ${{ steps.deploy-client.outputs.url }}"
          echo "Server deployed to: ${{ steps.deploy-server.outputs.url }}"